name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 1つ前のtagからの差分を取得
      - name: Get commit summary
        uses: ./.github/actions/commit-summary
        id: get_commit_summary
        with:
          ref: ${{ github.ref }}

      # 1つ前のtagからの差分を取得
      # - name: Get commit summary
      #   uses: Rasukarusan/commit-summary@v1
      #   id: get_commit_summary
      #   with:
      #     ref: ${{ github.ref }}

      # リリースノートの作成
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.get_commit_summary.outputs.summary }}
          draft: false
          prerelease: false

      # バイナリファイルのアップロード
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gitblamer
          asset_name: gitblamer
          asset_content_type: application/octet-stream

      # Formulaに値を渡す準備
      - name: Set value for formula
        id: set_value_for_formula
        run: |
          SHA256=$(openssl dgst -sha256 gitblamer | awk '{print $2}')
          echo ::set-output name=SHA256::$SHA256
          echo ::set-output name=BINARY::gitblamer
          echo ::set-output name=CLASS::Gitblamer

       # Formulaリポジトリ更新(Formulaリポジトリのworkflowを発火)
      - name: Update Formula Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Rasukarusan/homebrew-tap
          event-type: released
          client-payload: '
            {
              "ref": "${{ github.ref }}",
              "sha256": "${{ steps.set_value_for_formula.outputs.SHA256 }}",
              "binary": "${{ steps.set_value_for_formula.outputs.BINARY }}",
              "url": "${{ steps.create_release.outputs.upload_url }}",
              "class": "${{ steps.set_value_for_formula.outputs.CLASS }}"
            }
          '
