name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      tags:
       description: 'Test scenario tags'
jobs:
  myTestAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Hello world action step
        uses: ./.github/actions/commit-summary # Uses an action in the root directory
        id: hello
        with:
          ref: ${{ github.ref }}
      # 「hello」ステップの出力を使用する
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.summary }}"
